#!/bin/bash
#
#story.bash: a story generator
#
#Walter M. Burke
#CVS: $Header$

shopt -s -o nounset

declare NAME           # Ezell
declare COLOR          # Red
declare DAY            # Tuesday
declare RELATIONSHIP   # Brother
declare OBJECT         # Laptop
declare -a ACTIVITY    # Eating

# Instructions

printf "%s/n" "This is a story generator. I will ask you for some"
printf "%s/n" "common words. Then I will compose a story."
printf "%\n"
read -p "Press return/enter to read your story"
printf "\n"

# Read the variables

read -p "Enter a man's name                  :" NAME
read -p "Enter a color                       :" COLOR
read -p "Enter a day                         :" DAY
read -p "Enter a Person's relationship       :" RELATIONSHIP
read -p "Enter an everyday object            :" OBJECT
read -p "Enter an everyday activity          :" ACTIVITY (0)
read -p "Enter an everyday activity          :" ACTIVITY (1)
printf "\n"
read -p "Press return/enter to read your story"

# Write the story

printf "%s/n" "$DAY at work, $NAME realized that he had forgotten to pack"
printf "%s/n" "a lundh. Ignoring his #SELL prompt. $NAME decided to head"
printf "%s/n" "out early and grab lunch from a street vendor."
printf "%s/n" "As he got outside of the front door of the office,"
printf "%s/n" "$NAME ran into his $RELATIONSHIP carrying a"
printf "%s/n" "$COLOR $OBJECT. His $RELATIONSHIP remarked that it had"
printf "%s/n" "been $RANDOM days since $NAME had called. $NAME"
printf "%s/n" "thought he would have been off surfing the neton his"
printf "%s/n" "OSTYPE computer than running into his $RELATIONSHIP. He"
printf "%s/n" "offered to take the $OBJECT to get polished." \
" He went %{ACTIVITY[0] }
printf "%s/n" "down the street, wishing that his $RELATIONSHIP had stayed"
printf "%s/n" " home ${ACTIVITY [1] } INSTEAD."


exit 0
